include(joinpath(@__DIR__, "benchmark_legacy_engine.jl"))

const CANDIDATES = [
    "reward_heavy" => HeuristicWeights(),
    "codemyroad" => HeuristicWeights(
        reward=0.0076,
        aggregate_height=-0.510066,
        holes=-0.35663,
        bumpiness=-0.184483,
        max_height=0.0,
        wells=0.0,
        row_transitions=0.0,
        column_transitions=0.0,
        back_to_back=0.0,
    ),
    "dellacherie_proxy" => HeuristicWeights(
        reward=0.0085,
        aggregate_height=-0.25,
        holes=-7.90,
        bumpiness=0.0,
        max_height=-1.5,
        wells=-3.38,
        row_transitions=-3.22,
        column_transitions=-9.35,
        back_to_back=0.5,
    ),
    "balanced" => HeuristicWeights(
        reward=0.05,
        aggregate_height=-1.0,
        holes=-12.0,
        bumpiness=-1.0,
        max_height=-2.0,
        wells=-0.5,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=5.0,
    ),
    "survival" => HeuristicWeights(
        reward=0.0,
        aggregate_height=-0.5,
        holes=-8.0,
        bumpiness=-0.8,
        max_height=-2.0,
        wells=-0.5,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=0.0,
    ),
    "scoring" => HeuristicWeights(
        reward=0.12,
        aggregate_height=-1.2,
        holes=-18.0,
        bumpiness=-1.2,
        max_height=-3.0,
        wells=-0.8,
        row_transitions=-0.8,
        column_transitions=-1.5,
        back_to_back=12.0,
    ),
    "right_well" => HeuristicWeights(
        reward=1.0,
        aggregate_height=-0.2,
        holes=-60.0,
        bumpiness=0.0,
        max_height=-2.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=30.0,
        internal_bumpiness=-2.0,
        right_well_depth=12.0,
        right_column_height=-15.0,
    ),
    "right_well_aggressive" => HeuristicWeights(
        reward=2.0,
        aggregate_height=-0.1,
        holes=-80.0,
        bumpiness=0.0,
        max_height=-2.5,
        wells=0.0,
        row_transitions=-0.3,
        column_transitions=-0.8,
        back_to_back=80.0,
        internal_bumpiness=-2.5,
        right_well_depth=20.0,
        right_column_height=-25.0,
    ),
    "right_well_reserve_50" => HeuristicWeights(
        reward=1.0,
        aggregate_height=-0.2,
        holes=-60.0,
        bumpiness=0.0,
        max_height=-2.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=30.0,
        internal_bumpiness=-2.0,
        right_well_depth=12.0,
        right_column_height=-15.0,
        hold_i_reserve=50.0,
    ),
    "right_well_reserve_150" => HeuristicWeights(
        reward=1.0,
        aggregate_height=-0.2,
        holes=-80.0,
        bumpiness=0.0,
        max_height=-2.5,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=50.0,
        internal_bumpiness=-2.5,
        right_well_depth=16.0,
        right_column_height=-20.0,
        hold_i_reserve=150.0,
    ),
    "right_well_p100" => HeuristicWeights(
        reward=0.5,
        aggregate_height=-0.2,
        holes=-60.0,
        bumpiness=0.0,
        max_height=-2.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=30.0,
        internal_bumpiness=-2.0,
        right_well_depth=12.0,
        right_column_height=-15.0,
        tetris_clear=300.0,
        non_tetris_line=-100.0,
    ),
    "right_well_p250" => HeuristicWeights(
        reward=0.25,
        aggregate_height=-0.2,
        holes=-70.0,
        bumpiness=0.0,
        max_height=-2.5,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=50.0,
        internal_bumpiness=-2.0,
        right_well_depth=15.0,
        right_column_height=-20.0,
        tetris_clear=500.0,
        non_tetris_line=-250.0,
    ),
    "right_well_p500" => HeuristicWeights(
        reward=0.0,
        aggregate_height=-0.2,
        holes=-100.0,
        bumpiness=0.0,
        max_height=-3.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=100.0,
        internal_bumpiness=-2.5,
        right_well_depth=20.0,
        right_column_height=-25.0,
        tetris_clear=750.0,
        non_tetris_line=-500.0,
    ),
    "right_well_i50" => HeuristicWeights(
        reward=0.5,
        aggregate_height=-0.2,
        holes=-60.0,
        bumpiness=0.0,
        max_height=-2.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=30.0,
        internal_bumpiness=-2.0,
        right_well_depth=12.0,
        right_column_height=-15.0,
        tetris_clear=300.0,
        non_tetris_line=-100.0,
        wasted_i=-50.0,
    ),
    "right_well_i150" => HeuristicWeights(
        reward=0.5,
        aggregate_height=-0.2,
        holes=-70.0,
        bumpiness=0.0,
        max_height=-2.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=30.0,
        internal_bumpiness=-2.0,
        right_well_depth=12.0,
        right_column_height=-15.0,
        tetris_clear=300.0,
        non_tetris_line=-100.0,
        wasted_i=-150.0,
    ),
    "right_well_i300" => HeuristicWeights(
        reward=0.5,
        aggregate_height=-0.2,
        holes=-80.0,
        bumpiness=0.0,
        max_height=-2.5,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=50.0,
        internal_bumpiness=-2.5,
        right_well_depth=15.0,
        right_column_height=-20.0,
        tetris_clear=400.0,
        non_tetris_line=-120.0,
        wasted_i=-300.0,
    ),
    "right_well_flat4" => HeuristicWeights(
        reward=0.5,
        aggregate_height=-0.2,
        holes=-70.0,
        bumpiness=0.0,
        max_height=-2.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=30.0,
        internal_bumpiness=-4.0,
        right_well_depth=12.0,
        right_column_height=-15.0,
        tetris_clear=300.0,
        non_tetris_line=-100.0,
        left_stack_range=-4.0,
    ),
    "right_well_flat8" => HeuristicWeights(
        reward=0.5,
        aggregate_height=-0.2,
        holes=-80.0,
        bumpiness=0.0,
        max_height=-2.5,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=40.0,
        internal_bumpiness=-8.0,
        right_well_depth=15.0,
        right_column_height=-18.0,
        tetris_clear=350.0,
        non_tetris_line=-120.0,
        left_stack_range=-8.0,
    ),
    "right_well_flat15" => HeuristicWeights(
        reward=0.5,
        aggregate_height=-0.2,
        holes=-100.0,
        bumpiness=0.0,
        max_height=-3.0,
        wells=0.0,
        row_transitions=-0.5,
        column_transitions=-1.0,
        back_to_back=50.0,
        internal_bumpiness=-12.0,
        right_well_depth=20.0,
        right_column_height=-20.0,
        tetris_clear=400.0,
        non_tetris_line=-150.0,
        left_stack_range=-15.0,
    ),
]

function main()
    seed = parse(Int, get(ENV, "TUNE_SEED", "5742"))
    max_steps = parse(Int, get(ENV, "TUNE_MAX_STEPS", "250"))
    filter_text = get(ENV, "TUNE_FILTER", "")
    candidates = isempty(filter_text) ? CANDIDATES : filter(pair -> contains(pair.first, filter_text), CANDIDATES)
    results = Vector{NamedTuple}(undef, length(candidates))

    # One independent episode per candidate is a cheap screening gate. Promising
    # candidates are evaluated over multiple seeds in the next stage.
    Threads.@threads for index in eachindex(candidates)
        name, weights = candidates[index]
        elapsed = @elapsed episode = play_episode(seed, weights; max_steps=max_steps)
        results[index] = (; name, episode..., seconds=elapsed)
    end

    sort!(results; by=result -> result.score, rev=true)
    for result in results
        @printf("candidate=%-21s score=%6d steps=%3d lines=%3d tetrises=%2d i=%2d i_tetris=%2d holes=%2d maxh=%2d game_over=%-5s seconds=%7.3f\n",
            result.name, result.score, result.steps, result.lines_cleared,
            result.tetrises, result.i_placements, result.i_tetrises,
            result.final_holes, result.final_max_height, result.game_over, result.seconds)
    end
end

main()
